version: 1.1.{build}

branches:
  only:
    - main

environment:
  APPLE_ID_EMAIL: $APPLE_ID_EMAIL
  APPLE_ID_PASSWORD: $APPLE_ID_PASSWORD
  P12_BASE64: $P12_BASE64
  P12_PASSWORD: $P12_PASSWORD
  matrix:
    - job_name: Windows build
      job_group: Build
      jobs_per_group: 2
      appveyor_build_worker_image: Visual Studio 2022
    - job_name: macOS build
      job_group: Build
      jobs_per_group: 2
      appveyor_build_worker_image: macOS
    - job_name: Deploy Webhook
      appveyor_build_worker_image: Visual Studio 2022
      job_depends_on: Build

matrix:
  fast_finish: true

for:
  - 
    matrix:
      only:
        - job_name: Windows build
    init:
      - choco upgrade chocolatey
      - dotnet tool update -g checkbinarycompat
      - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
      - ps: '& $env:temp\dotnet-install.ps1 -Version "8.0.302"'
    build_script:
      - dotnet msbuild /p:Configuration=Release /clp:v=m MSBuildStructuredLog.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"
      - checkbinarycompat bin\StructuredLogViewer\Release\net472
    after_build:
      - ps: >-
          Compress-Archive `
          "bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogSetup.exe", `
          "bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogViewer*.nupkg", `
          "bin\StructuredLogger\Release\netstandard2.0\StructuredLogger.dll" `
          -DestinationPath "MSBuildStructuredLog-${Env:APPVEYOR_BUILD_VERSION}.zip"
    artifacts:
      - path: msbuild.binlog
        name: MSBuild Log
      - path: 'bin\StructuredLogViewer\Release\net472\msbuild-structured-log-viewer*.nupkg'
        name: Chocolatey Package
      - path: 'bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogSetup.exe'
        name: MSBuildStructuredLogSetup.exe
      - path: 'bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogViewer*.nupkg'
        name: Installer nupkg
      - path: 'bin\StructuredLogViewer\Release\net472\Releases\RELEASES'
        name: RELEASES
      - path: 'bin\StructuredLogger\Release\netstandard2.0\StructuredLogger.dll'
        name: StructuredLogger.dll
      - path: 'MSBuildStructuredLog-*.zip'
        name: Bundle
    on_failure:
      - appveyor PushArtifact msbuild.binlog

  - 
    matrix:
      only:
        - job_name: macOS build
    init:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | /bin/bash -s -- --channel 8.0
    build_script:
      - dotnet tool install Cake.Tool --create-manifest-if-needed
      - dotnet tool run dotnet-cake ./build-macos.cake --settings_skippackageversioncheck=true
    artifacts:
      - path: 'artifacts\StructuredLogViewer-*.zip'
        name: 'Structured Log Viewer macOS app'
    on_failure:
      - appveyor PushArtifact msbuild.binlog

  - 
    matrix:
      only:
        - job_name: Deploy Webhook
    deploy:
      - provider: Webhook
        url: https://app.signpath.io/API/v1/74f63071-f2aa-46ce-bd8f-1e7cd8774019/Integrations/AppVeyor?ProjectKey=MSBuildStructuredLog&SigningPolicyKey=release-signing
        authorization:
        secure: WALjHGjvNllt916kBDQ5tSYXGvaKDqymo/jQJoIKwITueSp4LF3jS+9nllR46G8pp2AH+Z6RL1f089XGDOYlfg==
